import { ClerkProvider } from '@clerk/nextjs';

export const metadata = {
  title: "factoryil",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // Asegúrate de que la variable de entorno esté disponible en tu código
  const clerkFrontendApi = process.env.NEXT_PUBLIC_CLERK_FRONTEND_API;
  //  <ClerkProvider > 
  
  return (
      <ClerkProvider frontendApi={clerkFrontendApi}>
      <html lang="es">
        <body>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
